# Monkey Pox

In [1]:
!pip install -q ipython-sql

In [2]:
# Importacao das bibliotecas
import pandas as pd
import sqlite3

In [3]:
# carregando o arquivo
# baixado em 14/08/2022
df = pd.read_csv("owid-monkeypox-data.csv")

In [4]:
# retorna as 10 primeiras linhas do arquivo
df.head(10)

,location,date,new_cases,new_cases_smoothed,total_cases,new_cases_per_million,total_cases_per_million,new_cases_smoothed_per_million,new_deaths,new_deaths_smoothed,total_deaths,new_deaths_per_million,total_deaths_per_million,new_deaths_smoothed_per_million
0,Andorra,2022-07-25,1.0,NaN,1.0,12.653,12.653,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Andorra,2022-07-26,2.0,NaN,3.0,25.306,37.958,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Andorra,2022-07-27,0.0,NaN,3.0,0.000,37.958,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Andorra,2022-07-28,0.0,NaN,3.0,0.000,37.958,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andorra,2022-07-29,0.0,NaN,3.0,0.000,37.958,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Andorra,2022-07-30,0.0,NaN,3.0,0.000,37.958,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Andorra,2022-07-31,0.0,0.43,3.0,0.000,37.958,5.441,NaN,NaN,NaN,NaN,NaN,NaN
7,Andorra,2022-08-01,0.0,0.29,3.0,0.000,37.958,3.669,NaN,NaN,NaN,NaN,NaN,NaN
8,Andorra,2022-08-02,0.0,0.00,3.0,0.000,37.958,0.000,NaN,NaN,NaN,NaN,NaN,NaN
9,Andorra,2022-08-03,0.0,0.00,3.0,0.000,37.958,0.000,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# retornar a quantidade de linhas e de colunas de um dataframe
df.shape

(3793, 14)

### Verificando valores nulos no dataframe

In [6]:
print(df.isna().sum())

location                              0
date                                  0
new_cases                             0
new_cases_smoothed                  436
total_cases                           0
new_cases_per_million                 0
total_cases_per_million               0
new_cases_smoothed_per_million      436
new_deaths                         3650
new_deaths_smoothed                3669
total_deaths                       3650
new_deaths_per_million             3650
total_deaths_per_million           3650
new_deaths_smoothed_per_million    3669
dtype: int64

### Imputação valores nulos

In [7]:
# a imputação foi feita trocando os valores "Nan" por 0. 
# Visto que os valores nulos são decorrentes dá não existência de dados do tipo númerico.
df = df.fillna(0, inplace = False)

### Procurando por mais algum valor nulo após a imputação

In [8]:
df.isna().sum()

location                           0
date                               0
new_cases                          0
new_cases_smoothed                 0
total_cases                        0
new_cases_per_million              0
total_cases_per_million            0
new_cases_smoothed_per_million     0
new_deaths                         0
new_deaths_smoothed                0
total_deaths                       0
new_deaths_per_million             0
total_deaths_per_million           0
new_deaths_smoothed_per_million    0
dtype: int64

In [9]:
# retornar o nome das colunas do dataframe
df.columns

Index(['location', 'date', 'new_cases', 'new_cases_smoothed', 'total_cases',
       'new_cases_per_million', 'total_cases_per_million',
       'new_cases_smoothed_per_million', 'new_deaths', 'new_deaths_smoothed',
       'total_deaths', 'new_deaths_per_million', 'total_deaths_per_million',
       'new_deaths_smoothed_per_million'],
      dtype='object')

In [10]:
# retorna informações a respeito das variáveis como tipos, valores não nulos e uso de memória
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3793 entries, 0 to 3792
Data columns (total 14 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   location                         3793 non-null   object
 1   date                             3793 non-null   object
 2   new_cases                        3793 non-null   float64
 3   new_cases_smoothed               3793 non-null   float64
 4   total_cases                      3793 non-null   float64
 5   new_cases_per_million            3793 non-null   float64
 6   total_cases_per_million          3793 non-null   float64
 7   new_cases_smoothed_per_million   3793 non-null   float64
 8   new_deaths                       3793 non-null   float64
 9   new_deaths_smoothed              3793 non-null   float64
 10  total_deaths                     3793 non-null   float64
 11  new_deaths_per_million           3793 non-null   float64
 12  total_deaths_per_million         3793 non-null   float64
 13  new_deaths_smoothed_per_million  3793 non-null   float64
dtypes: float64(12), object(2)
memory usage: 415.0+ KB

In [11]:
# carregando a extensão SQL
%load_ext sql

In [12]:
#remover, se já existir um banco de dados com o nome dbmonkeypox 
!rm 'db/dbmonkeypox.db'

In [13]:
#criando conexão banco de dados
con = sqlite3.connect('db/dbmonkeypox.db')

In [14]:
# Copia o dataframe como tabela pro banco. A saída mostra a quantidade de linhas carregadas
df.to_sql('monkeypox', con)

3793

In [15]:
# setando o banco de dados
%sql sqlite:///db/dbmonkeypox.db

### Estrutura da tabela

In [16]:
%%sql
SELECT * FROM pragma_table_info('monkeypox');

 * sqlite:///db/dbmonkeypox.db
Done.

[(0, 'index', 'INTEGER', 0, None, 0),
 (1, 'location', 'TEXT', 0, None, 0),
 (2, 'date', 'TEXT', 0, None, 0),
 (3, 'new_cases', 'REAL', 0, None, 0),
 (4, 'new_cases_smoothed', 'REAL', 0, None, 0),
 (5, 'total_cases', 'REAL', 0, None, 0),
 (6, 'new_cases_per_million', 'REAL', 0, None, 0),
 (7, 'total_cases_per_million', 'REAL', 0, None, 0),
 (8, 'new_cases_smoothed_per_million', 'REAL', 0, None, 0),
 (9, 'new_deaths', 'REAL', 0, None, 0),
 (10, 'new_deaths_smoothed', 'REAL', 0, None, 0),
 (11, 'total_deaths', 'REAL', 0, None, 0),
 (12, 'new_deaths_per_million', 'REAL', 0, None, 0),
 (13, 'total_deaths_per_million', 'REAL', 0, None, 0),
 (14, 'new_deaths_smoothed_per_million', 'REAL', 0, None, 0)]

### Select mostrando os primeiros 100 registros da tabela

In [17]:
%%sql

SELECT * FROM monkeypox LIMIT 100;

 * sqlite:///db/dbmonkeypox.db
Done.

[(0, 'Andorra', '2022-07-25', 1.0, 0.0, 1.0, 12.653, 12.653, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (1, 'Andorra', '2022-07-26', 2.0, 0.0, 3.0, 25.306, 37.958, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (2, 'Andorra', '2022-07-27', 0.0, 0.0, 3.0, 0.0, 37.958, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (3, 'Andorra', '2022-07-28', 0.0, 0.0, 3.0, 0.0, 37.958, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (4, 'Andorra', '2022-07-29', 0.0, 0.0, 3.0, 0.0, 37.958, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (5, 'Andorra', '2022-07-30', 0.0, 0.0, 3.0, 0.0, 37.958, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (6, 'Andorra', '2022-07-31', 0.0, 0.43, 3.0, 0.0, 37.958, 5.441, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (7, 'Andorra', '2022-08-01', 0.0, 0.29, 3.0, 0.0, 37.958, 3.669, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (8, 'Andorra', '2022-08-02', 0.0, 0.0, 3.0, 0.0, 37.958, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (9, 'Andorra', '2022-08-03', 0.0, 0.0, 3.0, 0.0, 37.958, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (10, 'Andorra', '2022-08-04', 0.0, 0.0, 3.0, 0.0, 37.958, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (11, 'Andorra', '2022-08-05', 0.0, 0.0, 3.0, 0.0, 37.958, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (12, 'Andorra', '2022-08-06', 0.0, 0.0, 3.0, 0.0, 37.958, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (13, 'Andorra', '2022-08-07', 0.0, 0.0, 3.0, 0.0, 37.958, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (14, 'Andorra', '2022-08-08', 1.0, 0.14, 4.0, 12.653, 50.611, 1.771, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (15, 'Argentina', '2022-05-27', 2.0, 0.0, 2.0, 0.044, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (16, 'Argentina', '2022-05-28', 0.0, 0.0, 2.0, 0.0, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (17, 'Argentina', '2022-05-29', 0.0, 0.0, 2.0, 0.0, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (18, 'Argentina', '2022-05-30', 0.0, 0.0, 2.0, 0.0, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (19, 'Argentina', '2022-05-31', 0.0, 0.0, 2.0, 0.0, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (20, 'Argentina', '2022-06-01', 0.0, 0.0, 2.0, 0.0, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (21, 'Argentina', '2022-06-02', 0.0, 0.29, 2.0, 0.0, 0.044, 0.006, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (22, 'Argentina', '2022-06-03', 0.0, 0.0, 2.0, 0.0, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (23, 'Argentina', '2022-06-04', 0.0, 0.0, 2.0, 0.0, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (24, 'Argentina', '2022-06-05', 0.0, 0.0, 2.0, 0.0, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (25, 'Argentina', '2022-06-06', 0.0, 0.0, 2.0, 0.0, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (26, 'Argentina', '2022-06-07', 0.0, 0.0, 2.0, 0.0, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (27, 'Argentina', '2022-06-08', 0.0, 0.0, 2.0, 0.0, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (28, 'Argentina', '2022-06-09', 1.0, 0.14, 3.0, 0.022, 0.066, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (29, 'Argentina', '2022-06-10', 0.0, 0.14, 3.0, 0.0, 0.066, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (30, 'Argentina', '2022-06-11', 0.0, 0.14, 3.0, 0.0, 0.066, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (31, 'Argentina', '2022-06-12', 0.0, 0.14, 3.0, 0.0, 0.066, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (32, 'Argentina', '2022-06-13', 0.0, 0.14, 3.0, 0.0, 0.066, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (33, 'Argentina', '2022-06-14', 0.0, 0.14, 3.0, 0.0, 0.066, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (34, 'Argentina', '2022-06-15', 0.0, 0.14, 3.0, 0.0, 0.066, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (35, 'Argentina', '2022-06-16', 0.0, 0.0, 3.0, 0.0, 0.066, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (36, 'Argentina', '2022-06-17', 0.0, 0.0, 3.0, 0.0, 0.066, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (37, 'Argentina', '2022-06-18', 0.0, 0.0, 3.0, 0.0, 0.066, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (38, 'Argentina', '2022-06-19', 0.0, 0.0, 3.0, 0.0, 0.066, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (39, 'Argentina', '2022-06-20', 0.0, 0.0, 3.0, 0.0, 0.066, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (40, 'Argentina', '2022-06-21', 1.0, 0.14, 4.0, 0.022, 0.088, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (41, 'Argentina', '2022-06-22', 0.0, 0.14, 4.0, 0.0, 0.088, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (42, 'Argentina', '2022-06-23', 0.0, 0.14, 4.0, 0.0, 0.088, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (43, 'Argentina', '2022-06-24', 0.0, 0.14, 4.0, 0.0, 0.088, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (44, 'Argentina', '2022-06-25', 0.0, 0.14, 4.0, 0.0, 0.088, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (45, 'Argentina', '2022-06-26', 0.0, 0.14, 4.0, 0.0, 0.088, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (46, 'Argentina', '2022-06-27', 0.0, 0.14, 4.0, 0.0, 0.088, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (47, 'Argentina', '2022-06-28', 1.0, 0.14, 5.0, 0.022, 0.11, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (48, 'Argentina', '2022-06-29', 0.0, 0.14, 5.0, 0.0, 0.11, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (49, 'Argentina', '2022-06-30', 1.0, 0.29, 6.0, 0.022, 0.133, 0.006, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (50, 'Argentina', '2022-07-01', 0.0, 0.29, 6.0, 0.0, 0.133, 0.006, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (51, 'Argentina', '2022-07-02', 0.0, 0.29, 6.0, 0.0, 0.133, 0.006, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (52, 'Argentina', '2022-07-03', 0.0, 0.29, 6.0, 0.0, 0.133, 0.006, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (53, 'Argentina', '2022-07-04', 0.0, 0.29, 6.0, 0.0, 0.133, 0.006, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (54, 'Argentina', '2022-07-05', 0.0, 0.14, 6.0, 0.0, 0.133, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (55, 'Argentina', '2022-07-06', 0.0, 0.14, 6.0, 0.0, 0.133, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (56, 'Argentina', '2022-07-07', 0.0, 0.0, 6.0, 0.0, 0.133, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (57, 'Argentina', '2022-07-08', 3.0, 0.43, 9.0, 0.066, 0.199, 0.009, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (58, 'Argentina', '2022-07-09', 0.0, 0.43, 9.0, 0.0, 0.199, 0.009, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (59, 'Argentina', '2022-07-10', 0.0, 0.43, 9.0, 0.0, 0.199, 0.009, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (60, 'Argentina', '2022-07-11', 0.0, 0.43, 9.0, 0.0, 0.199, 0.009, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (61, 'Argentina', '2022-07-12', 0.0, 0.43, 9.0, 0.0, 0.199, 0.009, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (62, 'Argentina', '2022-07-13', 3.0, 0.86, 12.0, 0.066, 0.265, 0.019, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (63, 'Argentina', '2022-07-14', 1.0, 1.0, 13.0, 0.022, 0.287, 0.022, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (64, 'Argentina', '2022-07-15', 0.0, 0.57, 13.0, 0.0, 0.287, 0.013, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (65, 'Argentina', '2022-07-16', 0.0, 0.57, 13.0, 0.0, 0.287, 0.013, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (66, 'Argentina', '2022-07-17', 0.0, 0.57, 13.0, 0.0, 0.287, 0.013, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (67, 'Argentina', '2022-07-18', 0.0, 0.57, 13.0, 0.0, 0.287, 0.013, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (68, 'Argentina', '2022-07-19', 0.0, 0.57, 13.0, 0.0, 0.287, 0.013, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (69, 'Argentina', '2022-07-20', 0.0, 0.14, 13.0, 0.0, 0.287, 0.003, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (70, 'Argentina', '2022-07-21', 0.0, 0.0, 13.0, 0.0, 0.287, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (71, 'Argentina', '2022-07-22', 5.0, 0.71, 18.0, 0.11, 0.398, 0.016, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (72, 'Argentina', '2022-07-23', 0.0, 0.71, 18.0, 0.0, 0.398, 0.016, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (73, 'Argentina', '2022-07-24', 0.0, 0.71, 18.0, 0.0, 0.398, 0.016, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (74, 'Argentina', '2022-07-25', 0.0, 0.71, 18.0, 0.0, 0.398, 0.016, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (75, 'Argentina', '2022-07-26', 2.0, 1.0, 20.0, 0.044, 0.442, 0.022, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (76, 'Argentina', '2022-07-27', 3.0, 1.43, 23.0, 0.066, 0.508, 0.032, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (77, 'Argentina', '2022-07-28', 0.0, 1.43, 23.0, 0.0, 0.508, 0.032, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (78, 'Argentina', '2022-07-29', 0.0, 0.71, 23.0, 0.0, 0.508, 0.016, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (79, 'Argentina', '2022-07-30', 0.0, 0.71, 23.0, 0.0, 0.508, 0.016, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (80, 'Argentina', '2022-07-31', 0.0, 0.71, 23.0, 0.0, 0.508, 0.016, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (81, 'Argentina', '2022-08-01', 0.0, 0.71, 23.0, 0.0, 0.508, 0.016, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (82, 'Argentina', '2022-08-02', 0.0, 0.43, 23.0, 0.0, 0.508, 0.009, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (83, 'Argentina', '2022-08-03', 14.0, 2.0, 37.0, 0.309, 0.817, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (84, 'Argentina', '2022-08-04', 0.0, 2.0, 37.0, 0.0, 0.817, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (85, 'Argentina', '2022-08-05', 0.0, 2.0, 37.0, 0.0, 0.817, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (86, 'Argentina', '2022-08-06', 0.0, 2.0, 37.0, 0.0, 0.817, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (87, 'Argentina', '2022-08-07', 0.0, 2.0, 37.0, 0.0, 0.817, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (88, 'Argentina', '2022-08-08', 0.0, 2.0, 37.0, 0.0, 0.817, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (89, 'Argentina', '2022-08-09', 0.0, 2.0, 37.0, 0.0, 0.817, 0.044, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (90, 'Argentina', '2022-08-10', 12.0, 1.71, 49.0, 0.265, 1.082, 0.038, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (91, 'Australia', '2022-05-20', 2.0, 0.0, 2.0, 0.077, 0.077, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (92, 'Australia', '2022-05-21', 0.0, 0.0, 2.0, 0.0, 0.077, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (93, 'Australia', '2022-05-22', 0.0, 0.0, 2.0, 0.0, 0.077, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (94, 'Australia', '2022-05-23', 0.0, 0.0, 2.0, 0.0, 0.077, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (95, 'Australia', '2022-05-24', 0.0, 0.0, 2.0, 0.0, 0.077, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (96, 'Australia', '2022-05-25', 0.0, 0.0, 2.0, 0.0, 0.077, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (97, 'Australia', '2022-05-26', 0.0, 0.29, 2.0, 0.0, 0.077, 0.011, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (98, 'Australia', '2022-05-27', 0.0, 0.0, 2.0, 0.0, 0.077, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (99, 'Australia', '2022-05-28', 0.0, 0.0, 2.0, 0.0, 0.077, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)]

### Qual é o total e a média de casos por país?

In [19]:
%%sql
SELECT location,
    SUM(total_cases) AS total_casos,
    ROUND(AVG(total_cases),2) AS media_casos 
    FROM monkeypox
    WHERE location <> "World"
    GROUP BY location
    ORDER BY media_casos DESC;

 * sqlite:///db/dbmonkeypox.db
Done.

[('United States', 159367.0, 1853.1),
 ('Spain', 154934.0, 1780.85),
 ('Germany', 103389.0, 1202.2),
 ('United Kingdom', 110652.0, 1129.1),
 ('France', 67291.0, 791.66),
 ('Brazil', 35653.0, 557.08),
 ('Canada', 32452.0, 381.79),
 ('Netherlands', 31811.0, 378.7),
 ('Portugal', 31589.0, 367.31),
 ('Italy', 18936.0, 220.19),
 ('Peru', 8233.0, 175.17),
 ('Belgium', 13440.0, 163.9),
 ('Switzerland', 10737.0, 127.82),
 ('Democratic Republic of Congo', 6114.0, 74.56),
 ('Israel', 4663.0, 56.87),
 ('Nigeria', 3550.0, 55.47),
 ('Austria', 4489.0, 54.74),
 ('Ireland', 2805.0, 38.96),
 ('Sweden', 3282.0, 38.61),
 ('Denmark', 2993.0, 36.5),
 ('Chile', 1693.0, 31.35),
 ('Mexico', 2259.0, 30.53),
 ('Poland', 1686.0, 27.64),
 ('Norway', 2001.0, 27.04),
 ('Ghana', 1532.0, 23.94),
 ('Australia', 1908.0, 22.71),
 ('Hungary', 1412.0, 19.89),
 ('Slovenia', 1324.0, 16.55),
 ('Greece', 964.0, 14.83),
 ('Romania', 875.0, 14.58),
 ('Puerto Rico', 572.0, 13.0),
 ('Luxembourg', 653.0, 11.66),
 ('Argentina', 870.0, 11.45),
 ('United Arab Emirates', 692.0, 11.16),
 ('Czechia', 855.0, 10.96),
 ('Colombia', 485.0, 10.32),
 ('Finland', 555.0, 7.93),
 ('Malta', 532.0, 7.29),
 ('Iceland', 285.0, 5.82),
 ('Singapore', 255.0, 5.43),
 ('Bolivia', 58.0, 4.83),
 ('Croatia', 163.0, 4.08),
 ('Serbia', 212.0, 4.0),
 ('Slovakia', 146.0, 3.95),
 ('Ecuador', 145.0, 3.92),
 ('India', 82.0, 3.9),
 ('Estonia', 164.0, 3.9),
 ('Cameroon', 67.0, 3.05),
 ('Lithuania', 27.0, 3.0),
 ('Benin', 3.0, 3.0),
 ('Andorra', 44.0, 2.93),
 ('Bulgaria', 87.0, 2.9),
 ('Saudi Arabia', 66.0, 2.54),
 ('Dominican Republic', 89.0, 2.47),
 ('New Zealand', 76.0, 2.24),
 ('Japan', 38.0, 2.24),
 ('Lebanon', 109.0, 2.18),
 ('Guatemala', 16.0, 2.0),
 ('Greenland', 2.0, 2.0),
 ('Central African Republic', 2.0, 2.0),
 ('Latvia', 93.0, 1.9),
 ('Qatar', 39.0, 1.86),
 ('South Africa', 35.0, 1.75),
 ('Thailand', 27.0, 1.69),
 ('Jamaica', 61.0, 1.69),
 ('Taiwan', 71.0, 1.61),
 ('Cyprus', 7.0, 1.4),
 ('Costa Rica', 9.0, 1.29),
 ('Uruguay', 7.0, 1.17),
 ('Turkey', 38.0, 1.12),
 ('Liberia', 18.0, 1.06),
 ('Panama', 36.0, 1.03),
 ('Venezuela', 1.0, 1.0),
 ('Sudan', 1.0, 1.0),
 ('South Korea', 1.0, 1.0),
 ('Russia', 1.0, 1.0),
 ('Philippines', 1.0, 1.0),
 ('New Caledonia', 1.0, 1.0),
 ('Morocco', 1.0, 1.0),
 ('Montenegro', 1.0, 1.0),
 ('Moldova', 1.0, 1.0),
 ('Georgia', 1.0, 1.0),
 ('Congo', 1.0, 1.0),
 ('Bosnia and Herzegovina', 1.0, 1.0),
 ('Bermuda', 1.0, 1.0),
 ('Barbados', 1.0, 1.0)]

### Qual é o total e a média de mortos por país?

In [20]:
%%sql
SELECT location,
    SUM(total_deaths) AS total_mortes,
    ROUND(AVG(total_deaths),2) AS media_mortes
    FROM monkeypox
    WHERE location <> "World"
    GROUP BY location
    ORDER BY total_mortes DESC;

 * sqlite:///db/dbmonkeypox.db
Done.

[('Nigeria', 109.0, 1.7),
 ('Spain', 3.0, 0.03),
 ('Peru', 1.0, 0.02),
 ('India', 1.0, 0.05),
 ('Ghana', 1.0, 0.02),
 ('Ecuador', 1.0, 0.03),
 ('Brazil', 1.0, 0.02),
 ('Venezuela', 0.0, 0.0),
 ('Uruguay', 0.0, 0.0),
 ('United States', 0.0, 0.0),
 ('United Kingdom', 0.0, 0.0),
 ('United Arab Emirates', 0.0, 0.0),
 ('Turkey', 0.0, 0.0),
 ('Thailand', 0.0, 0.0),
 ('Taiwan', 0.0, 0.0),
 ('Switzerland', 0.0, 0.0),
 ('Sweden', 0.0, 0.0),
 ('Sudan', 0.0, 0.0),
 ('South Korea', 0.0, 0.0),
 ('South Africa', 0.0, 0.0),
 ('Slovenia', 0.0, 0.0),
 ('Slovakia', 0.0, 0.0),
 ('Singapore', 0.0, 0.0),
 ('Serbia', 0.0, 0.0),
 ('Saudi Arabia', 0.0, 0.0),
 ('Russia', 0.0, 0.0),
 ('Romania', 0.0, 0.0),
 ('Qatar', 0.0, 0.0),
 ('Puerto Rico', 0.0, 0.0),
 ('Portugal', 0.0, 0.0),
 ('Poland', 0.0, 0.0),
 ('Philippines', 0.0, 0.0),
 ('Panama', 0.0, 0.0),
 ('Norway', 0.0, 0.0),
 ('New Zealand', 0.0, 0.0),
 ('New Caledonia', 0.0, 0.0),
 ('Netherlands', 0.0, 0.0),
 ('Morocco', 0.0, 0.0),
 ('Montenegro', 0.0, 0.0),
 ('Moldova', 0.0, 0.0),
 ('Mexico', 0.0, 0.0),
 ('Malta', 0.0, 0.0),
 ('Luxembourg', 0.0, 0.0),
 ('Lithuania', 0.0, 0.0),
 ('Liberia', 0.0, 0.0),
 ('Lebanon', 0.0, 0.0),
 ('Latvia', 0.0, 0.0),
 ('Japan', 0.0, 0.0),
 ('Jamaica', 0.0, 0.0),
 ('Italy', 0.0, 0.0),
 ('Israel', 0.0, 0.0),
 ('Ireland', 0.0, 0.0),
 ('Iceland', 0.0, 0.0),
 ('Hungary', 0.0, 0.0),
 ('Guatemala', 0.0, 0.0),
 ('Greenland', 0.0, 0.0),
 ('Greece', 0.0, 0.0),
 ('Germany', 0.0, 0.0),
 ('Georgia', 0.0, 0.0),
 ('France', 0.0, 0.0),
 ('Finland', 0.0, 0.0),
 ('Estonia', 0.0, 0.0),
 ('Dominican Republic', 0.0, 0.0),
 ('Denmark', 0.0, 0.0),
 ('Democratic Republic of Congo', 0.0, 0.0),
 ('Czechia', 0.0, 0.0),
 ('Cyprus', 0.0, 0.0),
 ('Croatia', 0.0, 0.0),
 ('Costa Rica', 0.0, 0.0),
 ('Congo', 0.0, 0.0),
 ('Colombia', 0.0, 0.0),
 ('Chile', 0.0, 0.0),
 ('Central African Republic', 0.0, 0.0),
 ('Canada', 0.0, 0.0),
 ('Cameroon', 0.0, 0.0),
 ('Bulgaria', 0.0, 0.0),
 ('Bosnia and Herzegovina', 0.0, 0.0),
 ('Bolivia', 0.0, 0.0),
 ('Bermuda', 0.0, 0.0),
 ('Benin', 0.0, 0.0),
 ('Belgium', 0.0, 0.0),
 ('Barbados', 0.0, 0.0),
 ('Austria', 0.0, 0.0),
 ('Australia', 0.0, 0.0),
 ('Argentina', 0.0, 0.0),
 ('Andorra', 0.0, 0.0)]

### Qual é a taxa de letalidade por localidade?

In [36]:
%%sql 
SELECT location, 
    SUM(total_cases) AS total_cases, 
    SUM(total_deaths) AS total_deaths,
    ROUND((SUM(total_deaths) / SUM(total_cases)) * 100,2) AS taxa_letalidade
    FROM monkeypox
    WHERE location <> "World"
    GROUP BY location 
    ORDER BY taxa_letalidade DESC;

 * sqlite:///db/dbmonkeypox.db
Done.

[('Nigeria', 3550.0, 109.0, 3.07),
 ('India', 82.0, 1.0, 1.22),
 ('Ecuador', 145.0, 1.0, 0.69),
 ('Ghana', 1532.0, 1.0, 0.07),
 ('Peru', 8233.0, 1.0, 0.01),
 ('Venezuela', 1.0, 0.0, 0.0),
 ('Uruguay', 7.0, 0.0, 0.0),
 ('United States', 159367.0, 0.0, 0.0),
 ('United Kingdom', 110652.0, 0.0, 0.0),
 ('United Arab Emirates', 692.0, 0.0, 0.0),
 ('Turkey', 38.0, 0.0, 0.0),
 ('Thailand', 27.0, 0.0, 0.0),
 ('Taiwan', 71.0, 0.0, 0.0),
 ('Switzerland', 10737.0, 0.0, 0.0),
 ('Sweden', 3282.0, 0.0, 0.0),
 ('Sudan', 1.0, 0.0, 0.0),
 ('Spain', 154934.0, 3.0, 0.0),
 ('South Korea', 1.0, 0.0, 0.0),
 ('South Africa', 35.0, 0.0, 0.0),
 ('Slovenia', 1324.0, 0.0, 0.0),
 ('Slovakia', 146.0, 0.0, 0.0),
 ('Singapore', 255.0, 0.0, 0.0),
 ('Serbia', 212.0, 0.0, 0.0),
 ('Saudi Arabia', 66.0, 0.0, 0.0),
 ('Russia', 1.0, 0.0, 0.0),
 ('Romania', 875.0, 0.0, 0.0),
 ('Qatar', 39.0, 0.0, 0.0),
 ('Puerto Rico', 572.0, 0.0, 0.0),
 ('Portugal', 31589.0, 0.0, 0.0),
 ('Poland', 1686.0, 0.0, 0.0),
 ('Philippines', 1.0, 0.0, 0.0),
 ('Panama', 36.0, 0.0, 0.0),
 ('Norway', 2001.0, 0.0, 0.0),
 ('New Zealand', 76.0, 0.0, 0.0),
 ('New Caledonia', 1.0, 0.0, 0.0),
 ('Netherlands', 31811.0, 0.0, 0.0),
 ('Morocco', 1.0, 0.0, 0.0),
 ('Montenegro', 1.0, 0.0, 0.0),
 ('Moldova', 1.0, 0.0, 0.0),
 ('Mexico', 2259.0, 0.0, 0.0),
 ('Malta', 532.0, 0.0, 0.0),
 ('Luxembourg', 653.0, 0.0, 0.0),
 ('Lithuania', 27.0, 0.0, 0.0),
 ('Liberia', 18.0, 0.0, 0.0),
 ('Lebanon', 109.0, 0.0, 0.0),
 ('Latvia', 93.0, 0.0, 0.0),
 ('Japan', 38.0, 0.0, 0.0),
 ('Jamaica', 61.0, 0.0, 0.0),
 ('Italy', 18936.0, 0.0, 0.0),
 ('Israel', 4663.0, 0.0, 0.0),
 ('Ireland', 2805.0, 0.0, 0.0),
 ('Iceland', 285.0, 0.0, 0.0),
 ('Hungary', 1412.0, 0.0, 0.0),
 ('Guatemala', 16.0, 0.0, 0.0),
 ('Greenland', 2.0, 0.0, 0.0),
 ('Greece', 964.0, 0.0, 0.0),
 ('Germany', 103389.0, 0.0, 0.0),
 ('Georgia', 1.0, 0.0, 0.0),
 ('France', 67291.0, 0.0, 0.0),
 ('Finland', 555.0, 0.0, 0.0),
 ('Estonia', 164.0, 0.0, 0.0),
 ('Dominican Republic', 89.0, 0.0, 0.0),
 ('Denmark', 2993.0, 0.0, 0.0),
 ('Democratic Republic of Congo', 6114.0, 0.0, 0.0),
 ('Czechia', 855.0, 0.0, 0.0),
 ('Cyprus', 7.0, 0.0, 0.0),
 ('Croatia', 163.0, 0.0, 0.0),
 ('Costa Rica', 9.0, 0.0, 0.0),
 ('Congo', 1.0, 0.0, 0.0),
 ('Colombia', 485.0, 0.0, 0.0),
 ('Chile', 1693.0, 0.0, 0.0),
 ('Central African Republic', 2.0, 0.0, 0.0),
 ('Canada', 32452.0, 0.0, 0.0),
 ('Cameroon', 67.0, 0.0, 0.0),
 ('Bulgaria', 87.0, 0.0, 0.0),
 ('Brazil', 35653.0, 1.0, 0.0),
 ('Bosnia and Herzegovina', 1.0, 0.0, 0.0),
 ('Bolivia', 58.0, 0.0, 0.0),
 ('Bermuda', 1.0, 0.0, 0.0),
 ('Benin', 3.0, 0.0, 0.0),
 ('Belgium', 13440.0, 0.0, 0.0),
 ('Barbados', 1.0, 0.0, 0.0),
 ('Austria', 4489.0, 0.0, 0.0),
 ('Australia', 1908.0, 0.0, 0.0),
 ('Argentina', 870.0, 0.0, 0.0),
 ('Andorra', 44.0, 0.0, 0.0)]

### Qual o percentual de mortes por dia?

In [43]:
%%sql
SELECT date,
       SUM(new_cases) as total_cases,
       SUM(new_deaths) as total_deaths,
       COALESCE((SUM(new_deaths)/SUM(new_cases))*100, 'NA') as PercentMortes
    FROM monkeypox
    WHERE location <> "World"
    GROUP BY date
    ORDER BY PercentMortes DESC;

 * sqlite:///db/dbmonkeypox.db
Done.

[('2022-05-22', 0.0, 0.0, 'NA'),
 ('2022-05-16', 0.0, 0.0, 'NA'),
 ('2022-05-14', 0.0, 0.0, 'NA'),
 ('2022-05-11', 0.0, 0.0, 'NA'),
 ('2022-05-10', 0.0, 0.0, 'NA'),
 ('2022-05-09', 0.0, 0.0, 'NA'),
 ('2022-05-07', 0.0, 0.0, 'NA'),
 ('2022-07-10', 27.0, 2.0, 7.4074074074074066),
 ('2022-05-29', 20.0, 1.0, 5.0),
 ('2022-07-30', 85.0, 2.0, 2.3529411764705883),
 ('2022-07-31', 131.0, 1.0, 0.7633587786259541),
 ('2022-07-28', 841.0, 1.0, 0.11890606420927466),
 ('2022-08-01', 1218.0, 1.0, 0.08210180623973727),
 ('2022-07-29', 1220.0, 1.0, 0.08196721311475409),
 ('2022-07-26', 1416.0, 1.0, 0.07062146892655367),
 ('2022-08-08', 1997.0, 1.0, 0.050075112669003496),
 ('2022-08-12', 684.0, 0.0, 0.0),
 ('2022-08-11', 669.0, 0.0, 0.0),
 ('2022-08-10', 1152.0, 0.0, 0.0),
 ('2022-08-09', 1433.0, 0.0, 0.0),
 ('2022-08-07', 125.0, 0.0, 0.0),
 ('2022-08-06', 113.0, 0.0, 0.0),
 ('2022-08-05', 1156.0, 0.0, 0.0),
 ('2022-08-04', 1123.0, 0.0, 0.0),
 ('2022-08-03', 653.0, 0.0, 0.0),
 ('2022-08-02', 1440.0, 0.0, 0.0),
 ('2022-07-27', 1272.0, 0.0, 0.0),
 ('2022-07-25', 1286.0, 0.0, 0.0),
 ('2022-07-24', 34.0, 0.0, 0.0),
 ('2022-07-23', 3.0, 0.0, 0.0),
 ('2022-07-22', 720.0, 0.0, 0.0),
 ('2022-07-21', 642.0, 0.0, 0.0),
 ('2022-07-20', 574.0, 0.0, 0.0),
 ('2022-07-19', 1194.0, 0.0, 0.0),
 ('2022-07-18', 817.0, 0.0, 0.0),
 ('2022-07-17', 38.0, 0.0, 0.0),
 ('2022-07-16', 16.0, 0.0, 0.0),
 ('2022-07-15', 888.0, 0.0, 0.0),
 ('2022-07-14', 611.0, 0.0, 0.0),
 ('2022-07-13', 418.0, 0.0, 0.0),
 ('2022-07-12', 872.0, 0.0, 0.0),
 ('2022-07-11', 591.0, 0.0, 0.0),
 ('2022-07-09', 122.0, 0.0, 0.0),
 ('2022-07-08', 1060.0, 0.0, 0.0),
 ('2022-07-07', 686.0, 0.0, 0.0),
 ('2022-07-06', 232.0, 0.0, 0.0),
 ('2022-07-05', 447.0, 0.0, 0.0),
 ('2022-07-04', 494.0, 0.0, 0.0),
 ('2022-07-03', 40.0, 0.0, 0.0),
 ('2022-07-02', 44.0, 0.0, 0.0),
 ('2022-07-01', 269.0, 0.0, 0.0),
 ('2022-06-30', 807.0, 0.0, 0.0),
 ('2022-06-29', 153.0, 0.0, 0.0),
 ('2022-06-28', 348.0, 0.0, 0.0),
 ('2022-06-27', 387.0, 0.0, 0.0),
 ('2022-06-26', 196.0, 0.0, 0.0),
 ('2022-06-25', 12.0, 0.0, 0.0),
 ('2022-06-24', 204.0, 0.0, 0.0),
 ('2022-06-23', 558.0, 0.0, 0.0),
 ('2022-06-22', 174.0, 0.0, 0.0),
 ('2022-06-21', 282.0, 0.0, 0.0),
 ('2022-06-20', 294.0, 0.0, 0.0),
 ('2022-06-19', 7.0, 0.0, 0.0),
 ('2022-06-18', 5.0, 0.0, 0.0),
 ('2022-06-17', 194.0, 0.0, 0.0),
 ('2022-06-16', 376.0, 0.0, 0.0),
 ('2022-06-15', 147.0, 0.0, 0.0),
 ('2022-06-14', 244.0, 0.0, 0.0),
 ('2022-06-13', 60.0, 0.0, 0.0),
 ('2022-06-12', 114.0, 0.0, 0.0),
 ('2022-06-11', 9.0, 0.0, 0.0),
 ('2022-06-10', 43.0, 0.0, 0.0),
 ('2022-06-09', 146.0, 0.0, 0.0),
 ('2022-06-08', 97.0, 0.0, 0.0),
 ('2022-06-07', 150.0, 0.0, 0.0),
 ('2022-06-06', 115.0, 0.0, 0.0),
 ('2022-06-05', 107.0, 0.0, 0.0),
 ('2022-06-04', 8.0, 0.0, 0.0),
 ('2022-06-03', 94.0, 0.0, 0.0),
 ('2022-06-02', 125.0, 0.0, 0.0),
 ('2022-06-01', 84.0, 0.0, 0.0),
 ('2022-05-31', 65.0, 0.0, 0.0),
 ('2022-05-30', 123.0, 0.0, 0.0),
 ('2022-05-28', 17.0, 0.0, 0.0),
 ('2022-05-27', 52.0, 0.0, 0.0),
 ('2022-05-26', 88.0, 0.0, 0.0),
 ('2022-05-25', 44.0, 0.0, 0.0),
 ('2022-05-24', 36.0, 0.0, 0.0),
 ('2022-05-23', 73.0, 0.0, 0.0),
 ('2022-05-21', 16.0, 0.0, 0.0),
 ('2022-05-20', 45.0, 0.0, 0.0),
 ('2022-05-19', 19.0, 0.0, 0.0),
 ('2022-05-18', 21.0, 0.0, 0.0),
 ('2022-05-17', 3.0, 0.0, 0.0),
 ('2022-05-15', 4.0, 0.0, 0.0),
 ('2022-05-13', 1.0, 0.0, 0.0),
 ('2022-05-12', 1.0, 0.0, 0.0),
 ('2022-05-08', 10.0, 0.0, 0.0),
 ('2022-05-06', 1.0, 0.0, 0.0)]

### Média móvel de casos Brasil

In [45]:
%%sql
SELECT date,
    location,
    new_cases,
    AVG(new_cases) OVER(PARTITION BY location ORDER BY date) as mediaMovelCasos
    FROM monkeypox
    WHERE location = 'Brazil';

 * sqlite:///db/dbmonkeypox.db
Done.

[('2022-06-08', 'Brazil', 1.0, 1.0),
 ('2022-06-09', 'Brazil', 0.0, 0.5),
 ('2022-06-10', 'Brazil', 0.0, 0.3333333333333333),
 ('2022-06-11', 'Brazil', 1.0, 0.5),
 ('2022-06-12', 'Brazil', 1.0, 0.6),
 ('2022-06-13', 'Brazil', 0.0, 0.5),
 ('2022-06-14', 'Brazil', 2.0, 0.7142857142857143),
 ('2022-06-15', 'Brazil', 0.0, 0.625),
 ('2022-06-16', 'Brazil', 1.0, 0.6666666666666666),
 ('2022-06-17', 'Brazil', 1.0, 0.7),
 ('2022-06-18', 'Brazil', 0.0, 0.6363636363636364),
 ('2022-06-19', 'Brazil', 1.0, 0.6666666666666666),
 ('2022-06-20', 'Brazil', 0.0, 0.6153846153846154),
 ('2022-06-21', 'Brazil', 1.0, 0.6428571428571429),
 ('2022-06-22', 'Brazil', 2.0, 0.7333333333333333),
 ('2022-06-23', 'Brazil', 5.0, 1.0),
 ('2022-06-24', 'Brazil', 1.0, 1.0),
 ('2022-06-25', 'Brazil', 2.0, 1.0555555555555556),
 ('2022-06-26', 'Brazil', 1.0, 1.0526315789473684),
 ('2022-06-27', 'Brazil', 0.0, 1.0),
 ('2022-06-28', 'Brazil', 1.0, 1.0),
 ('2022-06-29', 'Brazil', 16.0, 1.6818181818181819),
 ('2022-06-30', 'Brazil', 12.0, 2.130434782608696),
 ('2022-07-01', 'Brazil', 15.0, 2.6666666666666665),
 ('2022-07-02', 'Brazil', 12.0, 3.04),
 ('2022-07-03', 'Brazil', 2.0, 3.0),
 ('2022-07-04', 'Brazil', 2.0, 2.962962962962963),
 ('2022-07-05', 'Brazil', 26.0, 3.7857142857142856),
 ('2022-07-06', 'Brazil', 36.0, 4.896551724137931),
 ('2022-07-07', 'Brazil', 30.0, 5.733333333333333),
 ('2022-07-08', 'Brazil', 32.0, 6.580645161290323),
 ('2022-07-09', 'Brazil', 14.0, 6.8125),
 ('2022-07-10', 'Brazil', 0.0, 6.606060606060606),
 ('2022-07-11', 'Brazil', 10.0, 6.705882352941177),
 ('2022-07-12', 'Brazil', 38.0, 7.6),
 ('2022-07-13', 'Brazil', 42.0, 8.555555555555555),
 ('2022-07-14', 'Brazil', 39.0, 9.378378378378379),
 ('2022-07-15', 'Brazil', 0.0, 9.131578947368421),
 ('2022-07-16', 'Brazil', 0.0, 8.897435897435898),
 ('2022-07-17', 'Brazil', 0.0, 8.675),
 ('2022-07-18', 'Brazil', 0.0, 8.463414634146341),
 ('2022-07-19', 'Brazil', 101.0, 10.666666666666666),
 ('2022-07-20', 'Brazil', 143.0, 13.744186046511627),
 ('2022-07-21', 'Brazil', 13.0, 13.727272727272727),
 ('2022-07-22', 'Brazil', 90.0, 15.422222222222222),
 ('2022-07-23', 'Brazil', 0.0, 15.08695652173913),
 ('2022-07-24', 'Brazil', 0.0, 14.76595744680851),
 ('2022-07-25', 'Brazil', 115.0, 16.854166666666668),
 ('2022-07-26', 'Brazil', 56.0, 17.653061224489797),
 ('2022-07-27', 'Brazil', 112.0, 19.54),
 ('2022-07-28', 'Brazil', 89.0, 20.901960784313726),
 ('2022-07-29', 'Brazil', 193.0, 24.21153846153846),
 ('2022-07-30', 'Brazil', 84.0, 25.339622641509433),
 ('2022-07-31', 'Brazil', 27.0, 25.37037037037037),
 ('2022-08-01', 'Brazil', 105.0, 26.818181818181817),
 ('2022-08-02', 'Brazil', 128.0, 28.625),
 ('2022-08-03', 'Brazil', 118.0, 30.19298245614035),
 ('2022-08-04', 'Brazil', 139.0, 32.06896551724138),
 ('2022-08-05', 'Brazil', 144.0, 33.96610169491525),
 ('2022-08-06', 'Brazil', 104.0, 35.13333333333333),
 ('2022-08-07', 'Brazil', 23.0, 34.9344262295082),
 ('2022-08-08', 'Brazil', 162.0, 36.983870967741936),
 ('2022-08-09', 'Brazil', 122.0, 38.333333333333336),
 ('2022-08-10', 'Brazil', 43.0, 38.40625)]